name=me_MemoryAllocator
version=1.0.0
category=Other
architectures=*
sentence=Memory allocator. Experimental
paragraph=Adds global "HeapMem". Call "Heap.Init(<Heap_Size>)" to bring it to life.
url=https://github.com/martin-eden/Embedded-me_Heap
author=Martin Eden
maintainer=Martin Eden
depends=me_BaseTypes,me_Bits,me_WorkMemory,me_AddrsegTools,me_WorkmemTools
